src/utils/args_parser.h File Reference
#include <stdio.h>
#include <assert.h>
#include <string.h>
#include "statuses.h"
Classes
struct ArgsVars
Specifies variables, that are set from console arguments.
struct Argument
Specifies console argument parametres: name, function and description.
Enumerations
enum class ArgsMode { ERROR = -1
, EXIT = 0
, CONTINUE = 1
 }
Specifies int main() returns.
Functions
ArgsMode print_help (const Argument args_dict[], const int args_dict_len, int *arg_i, int argc, char *argv[], ArgsVars *args_vars)
Prints help.
ArgsMode read_input_filename (const Argument args_dict[], const int args_dict_len, int *arg_i, int argc, char *argv[], ArgsVars *args_vars)
Reads input file name from console.
ArgsMode read_output_filename (const Argument args_dict[], const int args_dict_len, int *arg_i, int argc, char *argv[], ArgsVars *args_vars)
Reads output file name from console.
Status::Statuses args_parse (int argc, char *argv[], ArgsVars *args_vars)
Parses console arguments.
Enumeration Type Documentation
ArgsMode
enum class ArgsMode [strong]
Specifies int main() returns.
Enumerator
ERROR Error.
EXIT Continue reading args, but then normal exit.
CONTINUE Continue reading args.
Definition at line 13 of file args_parser.h.
                    {
    ERROR = -1,
    EXIT = 0,
    CONTINUE = 1,
};
Function Documentation
args_parse()
Status::Statuses args_parse (int argc, char * argv[], ArgsVars * args_vars)
Parses console arguments.
Parameters
 in argc
 in argv
 out args_vars
Returns
Status::Statuses
This array contains console options, their functions and descriptions
< Help option
< Input filename
< Output filename
< args_dict array len
Definition at line 3 of file args_parser.cpp.
                                                                       {
    assert(argv);
    assert(argc);
    assert(args_vars);
    static Argument args_dict[] = {
        {"-h", print_help, "# -h - prints help information\n"},
        {"-i", read_input_filename, "# -i - specify input file name after this\n"},
        {"-o", read_output_filename, "# -o - specify output file name after this\n"},
    };
    static const int ARGS_DICT_LEN = sizeof(args_dict) / sizeof(args_dict[0]);
    bool exit = false;
    for (int i = 1; i < argc; i++) {
        bool is_found = false;
        for (int j = 0; j < ARGS_DICT_LEN; j++) {
            if (strcmp(argv[i], args_dict[j].arg) == 0) {
                switch (args_dict[j].func(args_dict, ARGS_DICT_LEN, &i, argc, argv, args_vars)) {
                    case ArgsMode::CONTINUE:
                        break;
                    case ArgsMode::EXIT:
                        exit = true;
                        break;
                    case ArgsMode::ERROR:
                        return Status::ARGS_ERROR;
                    default:
                        assert(0 && "args[j].func() returned wrong ArgsMode");
                        break;
                }
                is_found = true;
                break;
            }
        }
        if (is_found)
            continue;
        printf("Wrong console argument: %s\n"
               "Use -h for help\n", argv[i]);
        return Status::ARGS_ERROR;
    }
    if (exit)
        return Status::OK_EXIT;
    return Status::NORMAL_WORK;
}
References Status::ARGS_ERROR, CONTINUE, ERROR, EXIT, Status::NORMAL_WORK, Status::OK_EXIT, print_help(), read_input_filename(), and read_output_filename().
Referenced by main().
print_help()
ArgsMode print_help (const Argument args_dict[], const int args_dict_len, int * arg_i, int argc, char * argv[], ArgsVars * args_vars)
Prints help.
Parameters
 in args_dict
 in args_dict_len
 in arg_i number of current argument
 in argc int main() argc
 in argv int main() argv
 in args_vars
Returns
ArgsMode
Definition at line 56 of file args_parser.cpp.
                                                                                   {
    assert(args_dict);
    assert(arg_i);
    assert(argc);
    assert(argv);
    assert(args_vars);
    printf("# Onegin\n"
           "# Console args:\n");
    for (int i = 0; i < args_dict_len; i++)
        printf("%s", args_dict[i].description);
    printf("# End of help\n");
    return ArgsMode::EXIT;
}
References EXIT.
Referenced by args_parse().
read_input_filename()
ArgsMode read_input_filename (const Argument args_dict[], const int args_dict_len, int * arg_i, int argc, char * argv[], ArgsVars * args_vars)
Reads input file name from console.
Parameters
 in args_dict
 in args_dict_len
 in arg_i number of current argument
 in argc int main() argc
 in argv int main() argv
 out args_vars
Returns
ArgsMode
Definition at line 74 of file args_parser.cpp.
                                                                                      {
    (void) args_dict_len;
    assert(args_dict);
    assert(arg_i);
    assert(argv);
    assert(args_vars);
    if (++(*arg_i) >= argc) {
        printf("No input file name found\n");
        return ArgsMode::ERROR;
    }
    args_vars->input_filename = argv[*arg_i];
    return ArgsMode::CONTINUE;
}
References CONTINUE, ERROR, and ArgsVars::input_filename.
Referenced by args_parse().
read_output_filename()
ArgsMode read_output_filename (const Argument args_dict[], const int args_dict_len, int * arg_i, int argc, char * argv[], ArgsVars * args_vars)
Reads output file name from console.
Parameters
 in args_dict
 in args_dict_len
 in arg_i number of current argument
 in argc int main() argc
 in argv int main() argv
 out args_vars
Returns
ArgsMode
Definition at line 92 of file args_parser.cpp.
                                                                                       {
    (void) args_dict_len;
    assert(args_dict);
    assert(arg_i);
    assert(argv);
    assert(args_vars);
    if (++(*arg_i) >= argc) {
        printf("No output file name found\n");
        return ArgsMode::ERROR;
    }
    args_vars->output_filename = argv[*arg_i];
    return ArgsMode::CONTINUE;
}
References CONTINUE, ERROR, and ArgsVars::output_filename.
Referenced by args_parse().