file.cpp File Reference
#include file.h
Functions
Status::Statuses file_open_and_read (const char *filename, char **buf)
bool file_open_r (FILE **file, const char *filename)
Opens file in reading mode.
bool file_open_w (FILE **file, const char *filename)
Opens file in writing mode.
long file_get_len (FILE *file)
Gets file len.
bool file_read (FILE *file, char *buf, long file_len)
Reads data from char to buffer. Buffer must be big enough.
bool file_write_lines (FILE *file, String *lines)
Writes str (lines) array to file.
bool file_close (FILE *file)
Closes file.
Function Documentation
file_close()
bool file_close (FILE * file)
Closes file.
Parameters
file
Returns
true success
false failure
Definition at line 96 of file file.cpp.
                            {
    if (fclose(file) != 0) {
        perror("File close error");
        return false;
    }
    return true;
}
Referenced by file_open_and_read(), and main().
file_get_len()
long file_get_len (FILE * file)
Gets file len.
Parameters
file
Returns
long -1 in case of error
Definition at line 57 of file file.cpp.
                              {
    assert(file);
    long file_len = -1;
    if (fseek(file, 0, SEEK_END) != 0 ||
        (file_len = ftell(file)) == -1L ||
        fseek(file, 0, SEEK_SET) != 0) {
            perror("File len detection error");
            return -1;
    }
    return file_len;
}
Referenced by file_open_and_read().
file_open_and_read()
Status::Statuses file_open_and_read (const char * filename, char ** buf)
Definition at line 3 of file file.cpp.
                                                                    {
    FILE* file = nullptr;
    if (!file_open_r(&file, filename))
        return Status::FILE_ERROR;
    long file_len = file_get_len(file);
    if (file_len < 0) {
        file_close(file);
        return Status::FILE_ERROR;
    }
    *buf = (char*)calloc(file_len + 1, sizeof(char));
    if (*buf == nullptr) {
        printf("Memory alloc error\n");
        file_close(file);
        return Status::MEMORY_EXCEED;
    }
    if (!file_read(file, *buf, file_len)) {
        file_close(file);
        return Status::FILE_ERROR;
    }
    if (!file_close(file))
        return Status::FILE_ERROR;
    return Status::NORMAL_WORK;
}
References file_close(), Status::FILE_ERROR, file_get_len(), file_open_r(), file_read(), Status::MEMORY_EXCEED, and Status::NORMAL_WORK.
Referenced by main().
file_open_r()
bool file_open_r (FILE ** file, const char * filename)
Opens file in reading mode.
Parameters
file
filename
Returns
true success
false failure
Definition at line 33 of file file.cpp.
                                                    {
    assert(file);
    assert(filename);
    *file = fopen(filename, "rb");
    if (*file == nullptr) {
        printf("Error opening text file\n");
        return false;
    }
    return true;
}
Referenced by file_open_and_read().
file_open_w()
bool file_open_w (FILE ** file, const char * filename)
Opens file in writing mode.
Parameters
file
filename
Returns
true success
false failure
Definition at line 45 of file file.cpp.
                                                    {
    assert(file);
    assert(filename);
    *file = fopen(filename, "wb");
    if (*file == nullptr) {
        printf("Error opening text file\n");
        return false;
    }
    return true;
}
Referenced by main().
file_read()
bool file_read (FILE * file, char * buf, long file_len)
Reads data from char to buffer. Buffer must be big enough.
Parameters
file
buf
file_len
Returns
true
false
Definition at line 73 of file file.cpp.
                                                     {
    assert(file);
    assert(buf);
    size_t readed = fread(buf, sizeof(char), file_len, file);
    if (readed != (size_t)file_len || ferror(file)) {
        perror("File read error");
        return false;
    }
    return true;
}
Referenced by file_open_and_read().
file_write_lines()
bool file_write_lines (FILE * file, String * lines)
Writes str (lines) array to file.
Parameters
file
lines
Returns
true success
false failure
Definition at line 86 of file file.cpp.
                                                 {
    for (size_t i = 0; lines[i].str != nullptr; i++) {
        if (fprintf(file, "%s\n", lines[i].str) < 0) {
            printf("Error writing line to file");
            return false;
        }
    }
    return true;
}
References String::str.
Referenced by main().