src/file/file.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "../utils/statuses.h"
#include "../text/text_lib.h"
Functions
Status::Statuses file_open_read_close (const char *filename, char **buf, long *size=nullptr)
Opens files, reads and closes it.
bool file_open (FILE **file, const char *filename, const char *mode)
Opens file.
long file_get_len (FILE *file)
Gets file len.
bool file_read (FILE *file, char *buf, long file_len)
Reads data from char to buffer. Buffer must be big enough.
bool file_write_lines (FILE *file, String *lines)
Writes str (lines) array to file.
bool file_close (FILE *file)
Closes file.
Function Documentation
file_close()
bool file_close (FILE * file)
Closes file.
Parameters
file
Returns
true success
false failure
Definition at line 90 of file file.cpp.
                            {
    if (fclose(file) != 0) {
        perror("File close error");
        return false;
    }
    return true;
}
Referenced by file_open_read_close(), and main().
file_get_len()
long file_get_len (FILE * file)
Gets file len.
Parameters
file
Returns
long -1 in case of error
Definition at line 48 of file file.cpp.
                              {
    assert(file);
    long file_len = -1;
    if (fseek(file, 0, SEEK_END) != 0 ||
        (file_len = ftell(file)) == -1L ||
        fseek(file, 0, SEEK_SET) != 0) {
            perror("File len detection error");
            return -1;
    }
    return file_len;
}
Referenced by file_open_read_close().
file_open()
bool file_open (FILE ** file, const char * filename, const char * mode)
Opens file.
Parameters
file
filename
mode
Returns
true success
false failure
Definition at line 36 of file file.cpp.
                                                                    {
    assert(file);
    assert(filename);
    *file = fopen(filename, mode);
    if (*file == nullptr) {
        printf("Error opening text file\n");
        return false;
    }
    return true;
}
Referenced by file_open_read_close(), and main().
file_open_read_close()
Status::Statuses file_open_read_close (const char * filename, char ** buf, long * size = nullptr)
Opens files, reads and closes it.
Parameters
filename
buf
size
Returns
Status::Statuses
Definition at line 3 of file file.cpp.
                                                                                  {
    FILE* file = nullptr;
    if (!file_open(&file, filename, "rb"))
        return Status::FILE_ERROR;
    long file_len = file_get_len(file);
    if (file_len < 0) {
        file_close(file);
        return Status::FILE_ERROR;
    }
    if (size != nullptr)
        *size = file_len;
    *buf = (char*)calloc(file_len + 1, sizeof(char));
    if (*buf == nullptr) {
        printf("Memory alloc error\n");
        file_close(file);
        return Status::MEMORY_EXCEED;
    }
    if (!file_read(file, *buf, file_len)) {
        file_close(file);
        return Status::FILE_ERROR;
    }
    if (!file_close(file))
        return Status::FILE_ERROR;
    return Status::NORMAL_WORK;
}
References file_close(), Status::FILE_ERROR, file_get_len(), file_open(), file_read(), Status::MEMORY_EXCEED, and Status::NORMAL_WORK.
Referenced by InputData::ctor().
file_read()
bool file_read (FILE * file, char * buf, long file_len)
Reads data from char to buffer. Buffer must be big enough.
Parameters
file
buf
file_len
Returns
true
false
Definition at line 64 of file file.cpp.
                                                     {
    assert(file);
    assert(buf);
    size_t readed = fread(buf, sizeof(char), file_len, file);
    if (readed != (size_t)file_len || ferror(file)) {
        perror("File read error");
        return false;
    }
    return true;
}
Referenced by file_open_read_close().
file_write_lines()
bool file_write_lines (FILE * file, String * lines)
Writes str (lines) array to file.
Parameters
file
lines
Returns
true success
false failure
Definition at line 77 of file file.cpp.
                                                 {
    assert(file);
    assert(lines);
    for (size_t i = 0; lines[i].str != nullptr; i++) {
        if (fprintf(file, "%s\n", lines[i].str) < 0) {
            printf("Error writing line to file");
            return false;
        }
    }
    return true;
}
References String::str.
Referenced by main().