sort.h File Reference
#include <stdio.h>
#include <assert.h>
#include text_lib.h
Typedefs
typedef int comp_t(const void *a, const void *b)
Comparator func template.
Functions
int str_comp (const void *a, const void *b)
String comparator (uses strcmp_isalpha)
int str_comp_suf (const void *a, const void *b)
Suffix string comparator (uses strcmp_isalpha_suf)
int int_comp (const void *a, const void *b)
Int comparator.
void quick_sort (void *arr, size_t len, void *const pivot, size_t elem_size, comp_t *comp)
Quick sort algorithm.
void swap (void *a, void *b, size_t size)
Swaps variables.
Typedef Documentation
comp_t
typedef int comp_t(const void *a, const void *b)
Comparator func template.
Parameters
a
b
Returns
typedef
Definition at line 16 of file sort.h.
Function Documentation
int_comp()
int int_comp (const void * a, const void * b)
Int comparator.
Parameters
a
b
Returns
int
Definition at line 12 of file sort.cpp.
                                           {
    return *((const int*)a) - *((const int*)b);
}
quick_sort()
void quick_sort (void * arr, size_t len, void *const pivot, size_t elem_size, comp_t * comp)
Quick sort algorithm.
Parameters
arr data array pointer
len array len
pivot buffer variable
elem_size array element size
comp comparator func pointer
Definition at line 16 of file sort.cpp.
                                                                                          {
    if (len == 0 || len == 1) return;
    else if (len == 2) {
        if (comp(arr, (char*)arr + 1 * elem_size) > 0)
            swap(arr, (char*)arr + 1 * elem_size, elem_size);
        return;
    } else if (len == 3) {
        if (comp(arr, (char*)arr + 1 * elem_size) > 0)
            if (comp((char*)arr + 1 * elem_size, (char*)arr + 2 * elem_size) > 0) {
                swap(arr, (char*)arr + 2 * elem_size, elem_size);
            } else {
                swap(arr, (char*)arr + 1 * elem_size, elem_size);
                swap((char*)arr + 1 * elem_size, (char*)arr + 2 * elem_size, elem_size);
            }
        else if (comp((char*)arr + 1 * elem_size, (char*)arr + 2 * elem_size) > 0) {
            swap((char*)arr + 1 * elem_size, (char*)arr + 2 * elem_size, elem_size);
            swap(arr, (char*)arr + 1 * elem_size, elem_size);
        }
    }
    memcpy(pivot, (char*)arr, elem_size);
    size_t left = 0;
    size_t right = len - 1;
    while (1) {
        while (comp((char*)arr + left * elem_size, pivot) < 0) left++;
        while (comp(pivot, (char*)arr + right * elem_size) < 0) right--;
        if (left >= right) break;
        swap((char*)arr + left * elem_size, (char*)arr + right * elem_size, elem_size);
        left++;
        right--;
    }
    quick_sort(arr, right + 1, pivot, elem_size, comp);
    quick_sort((char*)arr + (right + 1) * elem_size, len - (right + 1), pivot, elem_size, comp);
}
References quick_sort(), and swap().
Referenced by main(), and quick_sort().
str_comp()
int str_comp (const void * a, const void * b)
String comparator (uses strcmp_isalpha)
Parameters
a
b
Returns
int
Definition at line 4 of file sort.cpp.
                                           {
    return strcmp_is_alpha(*(const char* const*)a, *(const char* const*)b);
}
References strcmp_is_alpha().
Referenced by main().
str_comp_suf()
int str_comp_suf (const void * a, const void * b)
Suffix string comparator (uses strcmp_isalpha_suf)
Parameters
a
b
Returns
int
Definition at line 8 of file sort.cpp.
                                               {
    return strcmp_is_alpha_suf(*(const char* const*)a, *(const char* const*)b);
}
References strcmp_is_alpha_suf().
Referenced by main().
swap()
void swap (void * a, void * b, size_t size) [inline]
Swaps variables.
Parameters
a
b
size
Definition at line 63 of file sort.h.
                                                {
    assert(a);
    assert(b);
    for (size_t i = 0; i < size; i++) {
        char c = ((char*)a)[i];
                 ((char*)a)[i] = ((char*)b)[i];
                                 ((char*)b)[i] = c;
    }
}
Referenced by quick_sort().