src/sort.cpp File Reference
#include sort.h
Functions
int string_comp (const void *a, const void *b)
String comparator (uses stringcmp_isalpha)
int string_comp_suf (const void *a, const void *b)
Suffix string comparator (uses stringcmp_isalpha_suf)
int int_comp (const void *a, const void *b)
Int comparator.
void quick_sort (void *array, size_t len, void *const pivot, size_t elem_size, comp_t *comp)
Quick sort algorithm.
void small_sort (void *array, size_t len, size_t elem_size, comp_t *comp)
Sorts an array of 2 or 3 elements.
void swap (void *a, void *b, size_t size)
Swaps variables.
Function Documentation
int_comp()
int int_comp (const void * a, const void * b)
Int comparator.
Parameters
a
b
Returns
int
Definition at line 11 of file sort.cpp.
                                           {
    return *((const int*)a) - *((const int*)b);
}
quick_sort()
void quick_sort (void * array, size_t len, void *const pivot, size_t elem_size, comp_t * comp)
Quick sort algorithm.
Parameters
array data array pointer
len array len
pivot buffer variable
elem_size array element size
comp comparator func pointer
Definition at line 15 of file sort.cpp.
                                                                                            {
    assert(array);
    assert(pivot);
    char* arr = (char*)array;
    if (len == 0 || len == 1) return;
    else if (len <= 3)
        small_sort(arr, len, elem_size, comp);
    swap(arr, arr + rand_normal_generate_ll(0, len - 1) * elem_size, elem_size);
    memcpy(pivot, arr, elem_size);
    size_t left = 0;
    size_t right = len - 1;
    while (1) {
        while (comp(arr + left * elem_size, pivot) < 0) left++;
        while (comp(pivot, arr + right * elem_size) < 0) right--;
        if (left >= right) break;
        swap(arr + left * elem_size, arr + right * elem_size, elem_size);
        left++;
        right--;
    }
    quick_sort(arr, right + 1, pivot, elem_size, comp);
    quick_sort(arr + (right + 1) * elem_size, len - (right + 1), pivot, elem_size, comp);
}
References quick_sort(), rand_normal_generate_ll(), small_sort(), and swap().
Referenced by main(), and quick_sort().
small_sort()
void small_sort (void * array, size_t len, size_t elem_size, comp_t * comp)
Sorts an array of 2 or 3 elements.
Parameters
array data array pointer
len array len
elem_size array element size
comp comparator func pointer
Definition at line 44 of file sort.cpp.
                                                                         {
    assert(array);
    assert(2 <= len && len <= 3);
    char* arr = (char*)array;
    if (len <= 3) {
        if(comp(arr, arr + 1 * elem_size) > 0)
            swap(arr, arr + 1 * elem_size, elem_size);
    }
    if (len == 3) {
        if(comp(arr + 1 * elem_size, arr + 2 * elem_size) > 0)
            swap(arr + 1 * elem_size, arr + 2 * elem_size, elem_size);
        if(comp(arr, arr + 1 * elem_size) > 0)
            swap(arr, arr + 1 * elem_size, elem_size);
    }
}
References swap().
Referenced by quick_sort().
string_comp()
int string_comp (const void * a, const void * b)
String comparator (uses stringcmp_isalpha)
Parameters
a
b
Returns
int
Definition at line 3 of file sort.cpp.
                                              {
    return stringcmp_is_alpha(*(const String*)a, *(const String*)b);
}
References stringcmp_is_alpha().
Referenced by main().
string_comp_suf()
int string_comp_suf (const void * a, const void * b)
Suffix string comparator (uses stringcmp_isalpha_suf)
Parameters
a
b
Returns
int
Definition at line 7 of file sort.cpp.
                                                  {
    return stringcmp_is_alpha_suf(*(const String*)a, *(const String*)b);
}
References stringcmp_is_alpha_suf().
Referenced by main().
swap()
void swap (void * a, void * b, size_t size)
Swaps variables.
Parameters
a
b
size
Definition at line 63 of file sort.cpp.
                                         {
    assert(a);
    assert(b);
    char* ca = (char*)a;
    char* cb = (char*)b;
    static_assert(sizeof(unsigned long long) == 8);
    size_t count = size >> 3;
    unsigned long long c = 0;
    for (size_t i = 0; i < count; i++) {
        memcpy(&c, ca + i * 8, 8);
            memcpy(ca + i * 8, cb + i * 8, 8);
                        memcpy(cb + i * 8, &c, 8);
    }
    if (size & 0x4) {
        static_assert(sizeof(int) == 4);
        int buf = 0;
        memcpy(&buf, ca + count * 8, 4);
              memcpy(ca + count * 8, cb + count * 8, 4);
                              memcpy(cb + count * 8, &buf, 4);
    } else if (size & 0x2) {
        static_assert(sizeof(short) == 2);
        short buf = 0;
        memcpy(&buf, ca + count * 8, 2);
              memcpy(ca + count * 8, cb + count * 8, 2);
                              memcpy(cb + count * 8, &buf, 2);
    } else if (size & 0x1) {
        char buf = 0;
        memcpy(&buf, ca + count * 8, 1);
              memcpy(ca + count * 8, cb + count * 8, 1);
                              memcpy(cb + count * 8, &buf, 1);
    }
}
Referenced by quick_sort(), and small_sort().