src/text/text_lib.cpp File Reference
#include "text_lib.h"
Functions
String my_strtok_line (const char *input)
Tokenizator for lines.
void split_text_to_lines (const char *text, String *lines_array)
Uses my_strtok_lines and writes results into array.
int stringcmp_is_alpha (String str1, String str2)
compares two strings, ignores non alpha symbols at the beginning
int stringcmp_is_alpha_suf (String str1, String str2)
compares two strings, goes from the end, ignores non alpha symbols at the beginning
Function Documentation
my_strtok_line()
String my_strtok_line (const char * str)
Tokenizator for lines.
Parameters
str
Returns
String
Definition at line 3 of file text_lib.cpp.
                                         {
    static char* str = nullptr;
    if (input != nullptr)
        str = const_cast<char*>(input);
    else
        input = str;
    if (str == nullptr)
        return String {};
    String ret = {};
    ret.str = str;
    while (*str != '\r' && *str != '\n')
        str++;
    while ((*str == '\r') && *str) {
        if (ret.len == 0)
            ret.len = str - input;
        *str = '\0';
        str++;
    }
    if (ret.len == 0)
        ret.len = str - input;
    *str = '\0';
    str++;
    if (*str == '\0')
        str = nullptr;
    return ret;
}
References String::len, and String::str.
Referenced by split_text_to_lines().
split_text_to_lines()
void split_text_to_lines (const char * text, String * lines_array)
Uses my_strtok_lines and writes results into array.
Parameters
text
lines_array
Definition at line 39 of file text_lib.cpp.
                                                                {
    assert(text);
    assert(lines_array);
    lines_array[0] = my_strtok_line(text);
    for (size_t i = 1; lines_array[i - 1].str != nullptr; i++) {
        lines_array[i] = my_strtok_line(nullptr);
    }
}
References my_strtok_line(), and String::str.
Referenced by InputData::ctor().
stringcmp_is_alpha()
int stringcmp_is_alpha (String str1, String str2)
compares two strings, ignores non alpha symbols at the beginning
Parameters
str1
str2
Returns
int
Definition at line 50 of file text_lib.cpp.
                                                 {
    assert(str1.str);
    assert(str2.str);
    str1.str = skip_non_alpha(str1.str);
    str2.str = skip_non_alpha(str2.str);
    return strcmp(str1.str, str2.str);
}
References skip_non_alpha(), and String::str.
Referenced by string_comp().
stringcmp_is_alpha_suf()
int stringcmp_is_alpha_suf (String str1, String str2)
compares two strings, goes from the end, ignores non alpha symbols at the beginning
Parameters
str1
str2
Returns
int
Definition at line 60 of file text_lib.cpp.
                                                     {
    assert(str1.str);
    assert(str2.str);
    str1.len = skip_non_alpha_from_end(str1.str, str1.len);
    str2.len = skip_non_alpha_from_end(str2.str, str2.len);
    while(str1.len > 0 && str2.len >0) {
        if (str1.str[str1.len - 1] != str2.str[str2.len - 1])
            return str1.str[str1.len - 1] - str2.str[str2.len - 1];
        str1.len--;
        str2.len--;
    }
    return (int)(str1.len - str2.len);
}
References String::len, skip_non_alpha_from_end(), and String::str.
Referenced by string_comp_suf().