text_lib.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <assert.h>
#include arrays.h
Classes
struct String
Struct to keep string and len together.
Functions
String my_strtok_line (const char *str)
Tokenizator for lines.
void split_text_to_lines_several_arrays (const char *text, String **lines_arrays, size_t lines_arrays_cnt)
Uses my_strtok_lines and writes results into several arrays.
bool create_lines_arrays (const char *text, String **lines_arrays, const size_t lines_array_size, const size_t lines_arrays_cnt)
Create a lines arrays object.
int stringcmp_is_alpha (String str1, String str2)
compares two strings, ignores non alpha symbols at the beginning
int stringcmp_is_alpha_suf (String str1, String str2)
compares two strings, goes from the end, ignores non alpha symbols at the beginning
size_t cntchar (const char *str, const char ch)
Counts ch in str.
char * skip_non_alpha (char *str)
Returns pointer at the first isalpha() symbol from str.
ssize_t skip_non_alpha_from_end (char *str, ssize_t len)
Returns len of str, but without non alpha symbols in the end.
Function Documentation
cntchar()
size_t cntchar (const char * str, const char ch) [inline]
Counts ch in str.
Parameters
str
ch
Returns
size_t
Definition at line 74 of file text_lib.h.
                                                      {
    size_t cnt = 0;
    for (size_t i = 0; str[i] != '\0'; i++)
        if (str[i] == ch)
            cnt++;
    return cnt;
}
Referenced by main().
create_lines_arrays()
bool create_lines_arrays (const char * text, String ** lines_arrays, const size_t lines_array_size, const size_t lines_arrays_cnt)
Create a lines arrays object.
Parameters
text
lines_arrays pointer to array of lines arrays
lines_array_size
lines_arrays_cnt
Returns
true success
false failure
Definition at line 56 of file text_lib.cpp.
                                                                                                                                {
    assert(text);
    assert(lines_arrays);
    if (!create_several_arrays((void**)lines_arrays, lines_array_size, lines_arrays_cnt, sizeof(String)))
        return false;
    split_text_to_lines_several_arrays(text, lines_arrays, lines_arrays_cnt);
    return true;
}
References create_several_arrays(), and split_text_to_lines_several_arrays().
Referenced by main().
my_strtok_line()
String my_strtok_line (const char * str)
Tokenizator for lines.
Parameters
str
Returns
String
Definition at line 3 of file text_lib.cpp.
                                         {
    static char* str = nullptr;
    if (input != nullptr)
        str = const_cast<char*>(input);
    else
        input = str;
    if (str == nullptr)
        return String {};
    String ret = {};
    ret.str = str;
    while (*str != '\r' && *str != '\n')
        str++;
    while ((*str == '\r') && *str) {
        if (ret.len == 0)
            ret.len = str - input;
        *str = '\0';
        str++;
    }
    if (ret.len == 0)
        ret.len = str - input;
    *str = '\0';
    str++;
    if (*str == '\0')
        str = nullptr;
    return ret;
}
References String::len, and String::str.
Referenced by split_text_to_lines_several_arrays().
skip_non_alpha()
char * skip_non_alpha (char * str) [inline]
Returns pointer at the first isalpha() symbol from str.
Parameters
str
Returns
char*
Definition at line 90 of file text_lib.h.
                                       {
    while (!isalpha(*str) && *str != '\0') str++;
    return str;
}
Referenced by stringcmp_is_alpha().
skip_non_alpha_from_end()
ssize_t skip_non_alpha_from_end (char * str, ssize_t len) [inline]
Returns len of str, but without non alpha symbols in the end.
Parameters
str
len
Returns
ssize_t
Definition at line 102 of file text_lib.h.
                                                               {
    while (--len >= 0 && !isalpha(str[len])) {}
    return len;
}
Referenced by stringcmp_is_alpha_suf().
split_text_to_lines_several_arrays()
void split_text_to_lines_several_arrays (const char * text, String ** lines_arrays, size_t lines_arrays_cnt)
Uses my_strtok_lines and writes results into several arrays.
Parameters
text
lines_arrays
lines_arrays_cnt
Definition at line 39 of file text_lib.cpp.
                                                                                                          {
    assert(text);
    assert(lines_arrays);
    lines_arrays[0][0] = my_strtok_line(text);
    size_t i = 1;
    do {
        lines_arrays[0][i] = my_strtok_line(nullptr);
        for (size_t j = 1; j < lines_arrays_cnt; j++)
            lines_arrays[j][i - 1] = lines_arrays[0][i - 1];
        i++;
    } while (lines_arrays[0][i - 1].str != nullptr);
}
References my_strtok_line().
Referenced by create_lines_arrays().
stringcmp_is_alpha()
int stringcmp_is_alpha (String str1, String str2)
compares two strings, ignores non alpha symbols at the beginning
Parameters
str1
str2
Returns
int
Definition at line 68 of file text_lib.cpp.
                                                 {
    assert(str1.str);
    assert(str2.str);
    str1.str = skip_non_alpha(str1.str);
    str2.str = skip_non_alpha(str2.str);
    return strcmp(str1.str, str2.str);
}
References skip_non_alpha(), and String::str.
Referenced by string_comp().
stringcmp_is_alpha_suf()
int stringcmp_is_alpha_suf (String str1, String str2)
compares two strings, goes from the end, ignores non alpha symbols at the beginning
Parameters
str1
str2
Returns
int
Definition at line 78 of file text_lib.cpp.
                                                     {
    assert(str1.str);
    assert(str2.str);
    str1.len = skip_non_alpha_from_end(str1.str, str1.len);
    str2.len = skip_non_alpha_from_end(str2.str, str2.len);
    while(str1.len >= 0 && str2.len >=0) {
        if (str1.str[str1.len] != str2.str[str2.len])
            return str1.str[str1.len] - str2.str[str2.len];
        str1.len--;
        str2.len--;
    }
    return (int)(str1.len - str2.len);
}
References String::len, skip_non_alpha_from_end(), and String::str.
Referenced by string_comp_suf().